apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: default
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repo
      taskSpec:
        workspaces:
          - name: output
        steps:
          - name: clear-dir
            image: busybox
            script: |
              rm -rf /workspace/output/*
          - name: clone
            image: alpine/git
            script: |
              git clone https://github.com/ashnike/Budget-App.git /workspace/output -b main
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image
      runAfter: [fetch-repo]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: docker.io/ashniike/budget-app:latest
      workspaces:
        - name: source
          workspace: shared-workspace
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    - name: push-image
      runAfter: [build-image]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: docker.io/ashniike/budget-app:latest
      workspaces:
        - name: source
          workspace: shared-workspace
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
